- hosts: all

  # Specifying a role will run all of the role’s tasks.
  roles:
      - system
      - lamp

  tasks:
    - name: set git config values
      template:
        src: files/gitconfig.j2
        dest: /home/vagrant/.gitconfig

      - name: copy profile files
        copy: src={{ item }} dest=/home/vagrant force=yes
        with_fileglob:
            - files/dot/.*

      # Add additional tasks as needed. For example,
      #
      # - name: install app dependencies
      #   command: composer install
      #   args:
      #       chdir: /var/www/{{ hostname }}

      # If you do not want to run all of a role’s tasks, include
      # a single task like this:
      #
      # - include: roles/nosql/tasks/install_redis.yml
